ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Models/Location.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ImmersiveQuiz.Models
{
    public class Location
    {
        public int LocationId { get; set; }

        public string Name { get; set; }

        public Guid ImageGuid { get; set; }

        public string ImageExtension { get; set; }

        public string ImagePath {
            get
            {
                return $"/images/{ImageGuid}{ImageExtension}";
            }
        }

        public int CourseId { get; set; }

        [NotMapped]
        public Course Course { get; set; }
    }
}

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ImmersiveQuiz.Data;
using ImmersiveQuiz.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Components;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace ImmersiveQuiz.Controllers
{
    [Authorize(Roles = "Verified")]
    public class LocationsController : Controller
    {
        private readonly LocationContext _locationContext;
        private readonly QuestionContext _questionContext;
        private readonly AnswerContext _answerContext;
        private readonly IWebHostEnvironment _webHostEnvironment;

      
        public LocationsController(LocationContext context, QuestionContext questionContext, AnswerContext answerContext, IWebHostEnvironment hostEnvironment)
        {
            _locationContext = context;
            _questionContext = questionContext;
            _answerContext = answerContext;
            _webHostEnvironment = hostEnvironment;
        }

        // GET: Locations
        public async Task<IActionResult> Index(string search)
        {
            var locations = from location in _locationContext.Location
                            select location;

            if (!string.IsNullOrEmpty(search))
            {
                locations = locations.Where(location => location.Name.Contains(search));
            }

            return View(await locations.ToListAsync());
        }

        // GET: Locations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _locationContext.Location
                .FirstOrDefaultAsync(m => m.LocationId == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        // GET: Locations/Create
        public IActionResult Create(int? id) // Passing in courseId
        {
            if (id == null)
            {
                return NotFound();
            }

            LocationImageViewModel vm = new LocationImageViewModel()
            {
                CourseId = id.Value
            };
            return View(vm);
        }

        // POST: Locations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LocationImageViewModel vm, int id)
        {
            if (ModelState.IsValid)
            {
                Location location = new Location()
                {
                    CourseId = id,
                    Name = vm.Name,
                    ImageGuid = UploadImage(vm.LocationImage),
                    ImageExtension = Path.GetExtension(vm.LocationImage.FileName)
                };
                _locationContext.Add(location);
                await _locationContext.SaveChangesAsync();
                return RedirectToAction("Details", "Courses", new { id = id });
            }
            return View(vm);
        }

        private Guid UploadImage(IFormFile image)
        {
            Guid imageGuid = Guid.NewGuid();
            string filePath = Path.Combine(Path.Combine(_webHostEnvironment.WebRootPath, "images"), imageGuid.ToString()) + Path.GetExtension(image.FileName);
            
            using var fileStream = new FileStream(filePath, FileMode.Create);
            image.CopyTo(fileStream);
            
            return imageGuid;
        }

        // GET: Locations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _locationContext.Location.FindAsync(id);
            if (location == null)
            {
                return NotFound();
            }

            
            LocationImageViewModel vm = new LocationImageViewModel()
            {
                CourseId = location.CourseId,
                LocationId = location.LocationId,
                Name = location.Name
            };

            return View(vm);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(LocationImageViewModel vm, int id) // passing in courseId
        {
           var location = _locationContext.Location.Find(vm.LocationId);
            try
            {

                location.Name = vm.Name;
                location.ImageGuid = UploadImage(vm.LocationImage);
                location.ImageExtension = Path.GetExtension(vm.LocationImage.FileName);

                _locationContext.Update(location);
                await _locationContext.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LocationExists(vm.LocationId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Details", "Courses", new { id = location.CourseId });
            
        }

        // GET: Locations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var location = await _locationContext.Location
                .FirstOrDefaultAsync(m => m.LocationId == id);
            if (location == null)
            {
                return NotFound();
            }

            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var location = await _locationContext.Location.FindAsync(id);

            var questionsToLocations = _questionContext.Question.Where(q => q.LocationId == location.LocationId);
            foreach (var question in questionsToLocations)
            {
                var answersToQuestion = _answerContext.Answer.Where(ans => ans.QuestionId == question.QuestionId);
                _answerContext.Answer.RemoveRange(answersToQuestion);

                _questionContext.Remove(question);
            }
            _locationContext.Location.Remove(location);

            await _answerContext.SaveChangesAsync();
            await _questionContext.SaveChangesAsync();
            await _locationContext.SaveChangesAsync();

            return RedirectToAction("Details", "Courses", new { id = location.CourseId });
        }

        private bool LocationExists(int id)
        {
            return _locationContext.Location.Any(e => e.LocationId == id);
        }
    }
}

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Views/Locations/Create.cshtml
@model ImmersiveQuiz.Models.LocationImageViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Location</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LocationImage" class="control-label"></label>
                    <div class="custom-file">
                        <input asp-for="LocationImage" class="form-control custom-file-input" />
                        <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>
                    <span asp-validation-for="LocationImage" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
</form>
    </div>
</div>

<div>
    <a asp-controller="Courses" asp-action="Details" asp-route-id="@Model.CourseId">Back to Course</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });  
    </script>
}

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Views/Locations/Delete.cshtml
@model ImmersiveQuiz.Models.Location

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Location</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LocationId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Courses" asp-action="Details" asp-route-id="@Model.CourseId">Back to Course</a>
    </form>
</div>

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Views/Locations/Details.cshtml
@model ImmersiveQuiz.Models.Location

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Location</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageGuid)
        </dt>
        <dd class="col-sm-8">
            <img src="@Model.ImagePath" height="100" width="100" asp-append-version="true" />
        </dd>
        <dd class="col-sm-2">
            <a href="@Model.ImagePath">View Image</a>
        </dd>
    </dl>
</div>
<div>
    <a class="badge large-badge bg-secondary text-light" asp-controller="Courses" asp-action="Details" asp-route-id="@Model.CourseId">Back to List</a> |
    <a class="badge large-badge bg-primary text-light" asp-action="Edit" asp-route-id="@Model.LocationId">Edit</a>
    <a class="badge large-badge bg-success text-light" asp-action="Create" asp-controller="Questions" asp-route-id="@Model.LocationId">Add Question</a>
</div>
@await Component.InvokeAsync("QuestionList", new { locationId = Model.LocationId.ToString(), search = ""}) 

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Views/Locations/Edit.cshtml
@model ImmersiveQuiz.Models.LocationImageViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Location</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LocationId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationImage" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="LocationImage" class="form-control custom-file-input" />
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <span asp-validation-for="LocationImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Courses" asp-action="Details" asp-route-id="@Model.CourseId">Back to Course</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
            $(".custom-file-input").on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            });
    </script>
}

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Views/Locations/Index.cshtml
@model IEnumerable<ImmersiveQuiz.Models.Location>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Locations" asp-action="Index" method="get">
    <p>
        Name: <input type="text" name="Search" />
        <input type="submit" value="Find" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImagePath)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.LocationId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.LocationId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>