ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Models/Answer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ImmersiveQuiz.Models
{
    public class Answer
    {
        public int AnswerId { get; set; }

        [DisplayName("Answer")]
        [Required(ErrorMessage = "Please add the answer content")]
        public string Content { get; set; }

        public int QuestionId { get; set; }

        [DisplayName("Correct Answer")]
        public bool IsCorrect { get; set; }

        [NotMapped]
        public Question Question { get; set; }
    }
}

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ImmersiveQuiz.Data;
using ImmersiveQuiz.Models;
using Microsoft.AspNetCore.Authorization;

namespace ImmersiveQuiz.Controllers
{
    [Authorize(Roles = "Verified")]
    public class AnswersController : Controller
    {
        
        private readonly AnswerContext _answerContext;
        private readonly QuestionContext _questionContext;
        private readonly LocationContext _locationContext;


        
        public AnswersController(AnswerContext context, QuestionContext questionContext, LocationContext locationContext)
        {
            _answerContext = context;
            _questionContext = questionContext;
            _locationContext = locationContext;
        }

        // GET: Answers
        public async Task<IActionResult> Index()
        {
            return View(await _answerContext.Answer.ToListAsync());
        }

        // GET: Answers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var answer = await _answerContext.Answer
                .FirstOrDefaultAsync(m => m.AnswerId == id);
            if (answer == null)
            {
                return NotFound();
            }

            answer.Question = _questionContext.Question.Find(answer.QuestionId);

            return View(answer);
        }

        // GET: Answers/Create
        public IActionResult Create(int? id) // passing in questionId
        {
            Answer answer = new Answer();

            if (id.HasValue)
            {
                answer.QuestionId = id.Value;
            }

            var question = _questionContext.Question.Find(answer.QuestionId);
            if (question == null)
            {
                return NotFound();
            }

            answer.Question = question;

            var location = _locationContext.Location.Find(answer.Question.LocationId);
            if (location == null)
            {
                return NotFound();
            }

            answer.Question.Location = location;

            return View(answer);
        }

        // POST: Answers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create(Answer answer, int id) // passing in question Id
        {
            answer.QuestionId = id;

            var answerCount = _answerContext.Answer.Count(x => x.QuestionId == id);

            var question = _questionContext.Question.Find(answer.QuestionId);
            if (question == null)
            {
                return NotFound();
            }

            answer.Question = question;

            var location = _locationContext.Location.Find(answer.Question.LocationId);
            if (location == null)
            {
                return NotFound();
            }

            answer.Question.Location = location;

            if (answerCount > 6)
            {
                ModelState.AddModelError("Answer", "Maximum number of answers reached!");
            }

            if (ModelState.IsValid)
            {
                _answerContext.Add(answer);
                await _answerContext.SaveChangesAsync();

                return RedirectToAction("Details", "Courses", new { id = location.CourseId });
            }
            return View(answer);
        }

        // GET: Answers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var answer = await _answerContext.Answer.FindAsync(id);
            if (answer == null)
            {
                return NotFound();
            }

            var question = await _questionContext.Question.FindAsync(answer.QuestionId);
            if (question == null)
            {
                return NotFound();
            }

            answer.Question = question;

            var location = _locationContext.Location.Find(answer.Question.LocationId);
            if (location == null)
            {
                return NotFound();
            }

            answer.Question.Location = location;

            return View(answer);
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AnswerId,IsCorrect,Content")] Answer answer)
        {
            if (id != answer.AnswerId)
            {
                return NotFound();
            }
            var ans = await _answerContext.Answer.FindAsync(answer.AnswerId);

            ans.IsCorrect = answer.IsCorrect;
            ans.Content = answer.Content;

            if (ModelState.IsValid)
            {
                try
                {
                    _answerContext.Update(ans);
                    await _answerContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnswerExists(ans.AnswerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                Question question = _questionContext.Question.First(q => q.QuestionId == ans.QuestionId);

                var location = _locationContext.Location.Find(question.LocationId);
                if (location == null)
                {
                    return NotFound();
                }

                return RedirectToAction("Details", "Courses", new { id = location.CourseId });
            }
            return View(answer);
        }

        // GET: Answers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var answer = await _answerContext.Answer
                .FirstOrDefaultAsync(m => m.AnswerId == id);
            if (answer == null)
            {
                return NotFound();
            }

            var question = await _questionContext.Question.FindAsync(answer.QuestionId);
            if (question == null)
            {
                return NotFound();
            }

            answer.Question = question;

            var location = _locationContext.Location.Find(answer.Question.LocationId);
            if (location == null)
            {
                return NotFound();
            }

            answer.Question.Location = location;

            return View(answer);
        }

        // POST: Answers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var answer = await _answerContext.Answer.FindAsync(id);
            _answerContext.Answer.Remove(answer);
            await _answerContext.SaveChangesAsync();
            Question question = _questionContext.Question.First(q => q.QuestionId == answer.QuestionId);

            var location = _locationContext.Location.Find(question.LocationId);
            if (location == null)
            {
                return NotFound();
            }

            return RedirectToAction("Details", "Courses", new { id = location.CourseId });
        }

        private bool AnswerExists(int id)
        {
            return _answerContext.Answer.Any(e => e.AnswerId == id);
        }
    }
}

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Views/Answers/Create.cshtml
@model ImmersiveQuiz.Models.Answer

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h3>Answer</h3>
<hr />
<h4>@Model.Question.Content</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IsCorrect" class="control-label"></label>
                @Html.CheckBoxFor(m => m.IsCorrect, new { @class="form-check large-checkbox"})
                <span asp-validation-for="IsCorrect" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Courses" asp-action="Details" asp-route-id="@Model.Question.Location.CourseId">Back to Course</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Views/Answers/Delete.cshtml
@model ImmersiveQuiz.Models.Answer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<hr />
<h4>@Model.Question.Content</h4>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsCorrect)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsCorrect)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AnswerId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Courses" asp-action="Details" asp-route-id="@Model.Question.Location.CourseId">Back to Course</a>
    </form>
</div>

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Views/Answers/Details.cshtml
@model ImmersiveQuiz.Models.Answer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h3>Answer</h3>
    <hr />
    <h4>@Model.Question.Content</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsCorrect)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsCorrect)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.AnswerId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Views/Answers/Edit.cshtml
@model ImmersiveQuiz.Models.Answer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h3>Answer</h3>
<hr />
<h4>@Model.Question.Content</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AnswerId" />
            <div class="form-group">
                <label asp-for="IsCorrect" class="control-label"></label>
                @Html.CheckBoxFor(m => m.IsCorrect, new { @class = "form-check large-checkbox" })
                <span asp-validation-for="IsCorrect" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Courses" asp-action="Details" asp-route-id="@Model.Question.Location.CourseId">Back to Course</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Views/Answers/Index.cshtml
@model IEnumerable<ImmersiveQuiz.Models.Answer>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuestionId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuestionId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.AnswerId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.AnswerId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.AnswerId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Views/Answers/Index2.cshtml
@model IQueryable<Answer>
@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.AnswerId).Titled("Answer ID");
        columns.Add(model => model.Content).Titled("Content");
        columns.Add(model => model.QuestionId).Titled("Question ID");
    })
    .Using(GridFilterMode.Header)
    .Empty("No data found")
    .Filterable()
    .Sortable()
    .Pageable()
)

<script>
    document.addEventListener("rowclick", e => {
        console.log(e);
       // e.detail.data - clicked row's data from columns.
        //e.detail.grid - grid's instance.
        //e.detail.originalEvent - original tr click event which triggered the rowclick.
    });
</script>

ImmersiveQuiz/ImmersiveQuiz/ImmersiveQuiz/Views/Answers/_AnswerRow.cshtml
@model ImmersiveQuiz.Models.Answer

<td>
    <input id="chkIsCorrect-@Model.AnswerId" asp-for="@Model.IsCorrect" class="form-control" />
</td>
<td>
    <input id="txtContent-@Model.AnswerId" asp-for="@Model.Content" class="form-control" />
</td>
<td>
    <button class="btn-update badge large-badge bg-primary text-light" data-id="@Model.AnswerId">Update</button>
    <a class="badge large-badge bg-danger text-light" asp-action="Delete" asp-controller="Answers" asp-route-id="@Model.AnswerId">Delete</a>
</td>